### ISSUE TITLE
Errors and not redirect after upgrade

### ISSUE THREAD

**Issue by gravinos** [sepiariver/redirectoid#3]
After the upgrade for 2.1.0 to 2.2.2 the script no longer works.

My code: 

![Schermata 2022-01-17 alle 16 25 45](https://user-images.githubusercontent.com/5929863/149797126-780e1a48-ec80-487d-a922-f82feaf7c347.png)

not redirect and have this errors:

```
ERROR /core/model/modx/modx.class.php | 1037
 `` is not a valid integer and may not be passed to makeUrl()

ERROR | /core/model/modx/modresponse.class.php | 210
Attempted to redirect to an empty URL.
```

Try with and without cache, same error and problem.

Component Version 2.2.2
MODX Revolution 2.8.3-pl
PHP 7.3

Thanks

**Comment by sepiariver** [comment]
please be assured that the use case you describe is supported and has been tested on thousands of implementations, especially with respect to php 7.3 and Revo 2.x

common causes:
- Is the Resource with ID 2 in the same Context as the Resource on which you are calling Redirectoid?
- Is the Resource with ID 2 not deleted and not belonging to any Resource Group nor other permissions schema?
- Does the Resource with ID 2 show up in your Context Cache?
- Is Redirectoid installed?

**Comment by gravinos** [comment]
Yes, all conditions are complied.

I uninstall the new version and go back to the previous 2.1.0 and the script works perfectly.

I have same problem in 15 installations!

**Comment by crimsonpixel** [comment]
I am also experiencing this problem when upgrading to 2.2.2 and I am on MODX 2.8.3 and php 7.4.  Will roll back to 2.1.0 in order to get this working correctly again.

**Comment by ovomatik** [comment]
For me, the redirection is working only if I have the property &useCtxMap=`1`

**Comment by sepiariver** [comment]
@gravadesign @crimsonpixel @ovomatik 

Thanks for reporting this and sorry for the issues. They should all be resolved in https://github.com/sepiariver/redirectoid/pull/4

New package being uploaded to MODX.com shortly :)
